### ISSUE TITLE
BUG - Component does not refresh when added outside of a form and moved in

### ISSUE THREAD

**Issue by melohagan** [chungchunwang/Budibase-QR-Code-Scanner#1]
1. Add the QR component to a blank screen
2. Add a form component
3. Drag the QR component into the form
4. Message is still shown - Form components need to be wrapped in a form

![Screenshot 2022-10-05 at 08 35 02](https://user-images.githubusercontent.com/101575380/194005739-a0b1b238-b1fe-4821-a1fe-f70fec4b32be.png)
![Screenshot 2022-10-05 at 08 35 27](https://user-images.githubusercontent.com/101575380/194005812-8b3291d7-c46a-449b-a040-1e9969521007.png)

A refresh of the screen does work.

**Comment by chungchunwang** [comment]
This should be fixed in the [new release](https://github.com/chungchunwang/Budibase-QR-Code-Scanner/releases/tag/v1.0.1)!
