### ISSUE TITLE
QR Code Data

### ISSUE THREAD

**Issue by kasgithub8** [chungchunwang/Budibase-QR-Code-Scanner#2]
Hi,

scanning works perfectly fine.
Do you plan on adding multi-scan?
Right now, adding multiple fields and QR-Fields in the new-row screen just shows the first one.

Sincerely,
Kevin

**Comment by chungchunwang** [comment]
Hi! Thanks for pointing out the bug. It should be fixed now in v1.0.2.

**Comment by kasgithub8** [comment]
> Hi! Thanks for pointing out the bug. It should be fixed now in v1.0.2.

I just updated and it doesn't work for me unfortunately, field just stays empty and shows the Label only.

**Comment by chungchunwang** [comment]
I cannot seem to recreate this, could you send me a screenshot?
This is what I see:
![724FEB05-6F43-4004-92E7-2FF0B084473C](https://user-images.githubusercontent.com/62127500/198437587-85e5034f-bf9f-4d87-b6f6-f5198fbb2835.jpeg)

**Comment by kasgithub8** [comment]
Hey @chungchunwang, 

it seems to work today!
I will keep you updated if something happens!
